<?php if (Mage::getStoreConfig('carriers/wuunderparcelshop/google_maps_api') != "" && false): ?>
    <script
        src="https://maps.googleapis.com/maps/api/js?key=<?php echo Mage::getStoreConfig('carriers/wuunderparcelshop/google_maps_api') ?>&sensor=false&v=3.13"
        type="text/javascript"></script>
<?php else: ?>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>
<?php endif; ?>