<?php if (Mage::getStoreConfig('carriers/wuunderparcelshop/google_maps_api') != ""): ?>
    <script
        src="https://maps.googleapis.com/maps/api/js?key=<?php echo Mage::getStoreConfig('carriers/wuunderparcelshop/google_maps_api') ?>"
        type="text/javascript"></script>
<?php else: ?>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>
<?php endif; ?>