<div id='parcelShopsContainer'>
    <?php echo $this->getOneStepCheckoutHtml(); ?>
    <div id='parcelShopsPopup'>
        <div id='parcelShopsPopupBar'>
            <table>
                <tr>
                    <td><span id='parcelShopsTitleLogo'></span><span id='parcelShopsTitleLogoChatbox'>Kies een parcelshop</span>
                        <div class="carrier-filter">Filter by:
                            <input type="checkbox" checked="checked" onchange="carrierFilterChange('DPD')">
                            <img src="<?php echo str_replace("index.php/", "", $this->getWebshopBaseUrl()); ?>skin/frontend/base/default/images/wuunder/dpd-logo.png" />
                            <input type="checkbox" checked="checked" onchange="carrierFilterChange('DHL_PARCEL')">
                            <img src="<?php echo str_replace("index.php/", "", $this->getWebshopBaseUrl()); ?>skin/frontend/base/default/images/wuunder/dhl-logo.png" />
                            <input type="checkbox" checked="checked" onchange="carrierFilterChange('POST_NL')">
                            <img src="<?php echo str_replace("index.php/", "", $this->getWebshopBaseUrl()); ?>skin/frontend/base/default/images/wuunder/postnl-logo.png" />
                        </div>
                        <span id='closeParcelshopPopup'></span>
                    </td>
                </tr>
                <tr>
                    <td><span id='parcelShopsSearchBarContainer'><input id='parcelShopsSearchBar' type='text'/><span
                                    id='submitParcelShopsSearchBar'>OK</span></span></td>
                </tr>
            </table>
        </div>
        <div id='parcelShopsMapLoader'>
            <div id='parcelShopOverlayLoader'></div>
        </div>
        <div id='parcelShopsMapContainer'>
            <div id='parcelShopsMap'></div>
        </div>
        <div id='parcelShopsList'>
            <div></div>
        </div>
    </div>
    <div id='parcelShopsSelectedContainer'>
        <?php echo $this->getCurrentParcelshopInfo(); ?>
        <a href='#' id='selectParceshop'
           onclick="showParcelshopPicker(event, '<?php echo $this->getWebshopBaseUrl(); ?>wuunderconnector/parcelshop/');">Klik
            hier om een parcelshop te selecteren</a>
    </div>
</div>